baseURL: 'http://example.org/'
languageCode: en-us
title: Apsan's Homepage
theme: Eclectic
enableEmoji: true

author:
  facebook: ' https://facebook.com/example'
  twitter: ' https://twitter.com/example'
  email: contact@example.org
  name: Apsan's Homepage
  location: Denver
  phone: (999) 990-9999
  hours: 'Mon-Fri: 9:00AM - 6:00PM, ET'
menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 99
    - identifier: blog
      name: Blog
      url: /blog
      weight: 200
params:
  color: '#4f46e5'
  copyright: Copyright &copy; 2022 Acme Corporation.   All Rights Reserved.
  footer:
    - title: About
      content: Acme Corporation is the
    - title: Recent Blog Posts
      recents: blog
      recentCount: 7
    - title: Contact Us
      contact: true
